### ISSUE TITLE
SQL Issue

### ISSUE THREAD

**Issue by BeercU** [spiritLHLS/convoypanel-scripts#3]
The Script installer runs fine, but it cant connect to SQL.

No Connection to the Database.

  SQLSTATE[HY000] [1045] Access denied for user 'btywda'@'172.20.0.2' (using password: YES) (Connection: mysql, SQL: select * from information_schema.tables where table_schema = hdtaag and table_name = migrations and table_type = 'BAS
  E TABLE')

**Comment by spiritLHLS** [comment]
I'll test it later.

**Comment by spiritLHLS** [comment]
I didn't have the problem you mentioned and everything installed fine.
